### PR TITLE
Header and css for login

### PR DESCRIPTION
**Pull request by Sihellman**
added css.
made Switcher.css, because LoginPage and SignUp are on the same page and need to share a css file, which is preferable to having the css in index.css.

### CODE REVIEW

**Review by DevorahLevi — APPROVED** [review]
Great job!

**Comment by Sihellman** [comment]
😊

On Mar 10, 2021 5:47 PM, DevorahLevi ***@***.***> wrote:

@DevorahLevi approved this pull request.

Great job!

**Review by thecomputerguyjeff — APPROVED** [review]
Firstly, love the commit messages. I can see exactly what you are doing. 

"Switcher" is a funny name, I see where you got it... Usually we create a routes.js file to handle that stuff, but I'm gonna tell everyone at work to call it Switcher :)

Go ahead and merge this in. I'm going to probably do a bit of refactor around some of our routing and 'switching' befor eSunday and talk through it in class.

**Comment by Sihellman** [comment]
thank you!!

**Pull request merged**
